### ISSUE TITLE
Running ImaGene w/ large samples and simulations

### ISSUE THREAD

**Issue by sdtemple** [mfumagalli/ImaGene#7]
I am trying to train ImaGene with 1000 chromosomes from a European-American like population. I have ~ 2 million simulations in ms format, occupying ~96 Gb of memory. First, I am curious about how to implement on high performance clusters. The main difference I see in the Reproduce/HPC/ code is this: `from keras import backend as K`. Versus I tried to implement distributed training w/

```
import tensorflow as tf
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
     # model set up
     pass
```

Second, for ImaGene, what drives the memory usage? In experimentation, for 100k simulations of 1k chromosomes with 200kb and 12 CPUs, ImaGene trained 1 epoch with batch size 32 in 7 hours and 13 minutes using 108 Gb of RAM. For 10k simulations of 200 chromosomes with 200 kb and 16 CPUs, ImaGene trained 1 epoch with batch size 32 in 6.5 minutes using 2.6 Gb of RAM.

**Comment by mfumagalli** [comment]
The files in the Reproduce/HPC folder are for reproducibility purposes only and have not been properly designed or optimised to be run on HPC.

ImaGene objects are large because they contain several pieces of information that are often not used for training. However, they are retained for experimenting and propotyping new approaches. In fact, I mostly use ImaGene for educational purposes now and not for production or large-scale deployments. Other implementations by other authors are more efficient and should be used for such cases.
________________________________
From: Seth D. Temple ***@***.***>
Sent: 03 November 2023 12:25 AM
To: mfumagalli/ImaGene ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mfumagalli/ImaGene] Running ImaGene w/ large samples and simulations (Issue #7)


I am trying to train ImaGene with 1000 chromosomes from a European-American like population. I have ~ 2 million simulations in ms format, occupying ~96 Gb of memory. First, I am curious about how to implement on high performance clusters. The main difference I see in the Reproduce/HPC/ code is this: from keras import backend as K. Versus I tried to implement distributed training w/

import tensorflow as tf
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
     # model set up
     pass


Second, for ImaGene, what drives the memory usage? In experimentation, for 100k simulations of 1k chromosomes with 200kb and 12 CPUs, ImaGene trained 1 epoch with batch size 32 in 7 hours and 13 minutes using 108 Gb of RAM. For 10k simulations of 200 chromosomes with 200 kb and 16 CPUs, ImaGene trained 1 epoch with batch size 32 in 6.5 minutes using 2.6 Gb of RAM.
